# Generated by Django 5.2.12 on 2026-06-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoseData',
        ),
    ]
